payum:
    storages:
        App\Entity\Payment: { doctrine: orm }
    security:
        token_storage:
            App\Entity\PaymentToken: { doctrine: orm }
    gateways:
        offline:
            factory: offline
        stripe:
            factory: stripe_checkout
            publishable_key: '%env(STRIPE_PUBLISHABLE_KEY)%'
            secret_key: '%env(STRIPE_SECRET_KEY)%'
        stripe_checkout_session:
            factory: stripe_checkout_session
            publishable_key: '%env(STRIPE_PUBLISHABLE_KEY)%'
            secret_key: '%env(STRIPE_SECRET_KEY)%'
            webhook_secret_keys:
                - '%env(STRIPE_WEBHOOK)%'
    dynamic_gateways:
        config_storage:
            App\Entity\GatewayConfig: { doctrine: orm }
